import { useEffect, useMemo, useState } from 'react';
import { Award, FileText, Loader2, Printer, Save, Search } from 'lucide-react';
import apiService from '../../services/api';
import { useNotifications } from '../../hooks/useNotifications';

const dateLabel = (value) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('fr-FR') : '—';
const ReportCardsPanel = ({ canManage }) => {
  const { success, error: notifyError } = useNotifications();
  const [loading, setLoading] = useState(true);
  const [loadingReport, setLoadingReport] = useState(false);
  const [refs, setRefs] = useState({ years: [], terms: [], students: [] });
  const [filter, setFilter] = useState({ academic_year_id: '', term_id: '', student_id: '' });
  const [report, setReport] = useState(null);
  const [meta, setMeta] = useState({ appreciation: '', decision: '', status: 'draft' });

  useEffect(() => { (async () => { try { const response = await apiService.getReportCardReferences(); const data=response.data||{}; setRefs(data); const year=data.years?.find((item)=>Number(item.is_active)===1)||data.years?.[0]; setFilter((current)=>({ ...current, academic_year_id: year?.id||'', student_id: data.students?.[0]?.id||'' })); } catch(err){ notifyError(err.message); } finally { setLoading(false); } })(); }, [notifyError]);
  const terms = useMemo(() => refs.terms.filter((term) => String(term.academic_year_id) === String(filter.academic_year_id)), [filter.academic_year_id, refs.terms]);
  useEffect(() => { if (terms.length && !terms.some((term)=>String(term.id)===String(filter.term_id))) setFilter((current)=>({ ...current, term_id: terms[0].id })); }, [terms, filter.term_id]);
  const load = async () => { if (!filter.student_id || !filter.academic_year_id || !filter.term_id) return notifyError('Sélectionnez l’élève, l’année et la période.'); try { setLoadingReport(true); const response=await apiService.getReportCard(filter); setReport(response.data); setMeta(response.data.metadata||{appreciation:'',decision:'',status:'draft'}); } catch(err){ notifyError(err.message); setReport(null); } finally { setLoadingReport(false); } };
  const save = async (status = meta.status) => { try { await apiService.saveReportCard({ ...filter, ...meta, status }); success(status === 'published' ? 'Bulletin publié.' : 'Brouillon enregistré.'); await load(); } catch(err){ notifyError(err.message); } };

  if (loading) return <div className="p-12 text-center"><Loader2 className="animate-spin mx-auto text-purple-600" /></div>;
  return <div className="space-y-5">
    <div className="rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800 p-5"><div><h2 className="text-3xl font-bold">Bulletins des étudiants</h2><p className="text-gray-500">Moyennes normalisées sur 20, coefficients des matières, classement, absences, appréciation et décision.</p></div><div className="grid md:grid-cols-4 gap-3 mt-5"><Select label="Année scolaire" value={filter.academic_year_id} onChange={(value)=>setFilter({...filter,academic_year_id:value,term_id:''})} options={refs.years.map((item)=>({id:item.id,name:item.name}))}/><Select label="Période" value={filter.term_id} onChange={(value)=>setFilter({...filter,term_id:value})} options={terms}/><Select label="Étudiant" value={filter.student_id} onChange={(value)=>setFilter({...filter,student_id:value})} options={refs.students.map((item)=>({id:item.id,name:`${item.last_name} ${item.first_name} — ${item.student_number}`}))}/><div className="flex items-end"><button onClick={load} disabled={loadingReport} className="w-full inline-flex justify-center items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 text-white font-bold">{loadingReport?<Loader2 size={18} className="animate-spin"/>:<Search size={18}/>} Générer / ouvrir</button></div></div></div>
    {!report && <div className="rounded-2xl border-2 border-dashed dark:border-gray-700 p-14 text-center text-gray-500"><FileText size={48} className="mx-auto mb-3 text-gray-300"/><h3 className="text-xl font-bold text-gray-700 dark:text-gray-200">Choisissez un étudiant et une période</h3><p>Le bulletin sera calculé à partir des notes réellement enregistrées.</p></div>}
    {report && <article className="school-print-area rounded-2xl border dark:border-gray-700 bg-white text-gray-900 overflow-hidden shadow-sm">
      <header className="bg-gradient-to-r from-purple-700 to-blue-700 text-white p-6 flex flex-wrap justify-between gap-4"><div><p className="text-sm uppercase tracking-widest opacity-80">Bulletin scolaire</p><h2 className="text-3xl font-bold">{report.student.first_name} {report.student.last_name}</h2><p>{report.student.student_number} · {report.student.level_name||'Niveau non renseigné'} {report.student.group_name?`— ${report.student.group_name}`:''}</p></div><div className="text-right"><strong className="block text-xl">{report.term.academic_year_name}</strong><span>{report.term.name}</span><small className="block">{dateLabel(report.term.start_date)} au {dateLabel(report.term.end_date)}</small></div></header>
      <div className="p-6"><div className="overflow-x-auto rounded-xl border"><table className="w-full"><thead className="bg-gray-50"><tr>{['Code','Matière','Évaluations','Coefficient','Moyenne / 20','Appréciation'].map((h)=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{report.course_results.map((row)=><tr key={row.course_id} className="border-t"><td className="p-3">{row.code}</td><td className="p-3 font-bold">{row.course_name}</td><td className="p-3">{row.evaluation_count}</td><td className="p-3">{row.coefficient}</td><td className="p-3 font-bold">{row.average == null?'Non noté':Number(row.average).toFixed(2)}</td><td className="p-3">{row.average==null?'—':row.average>=16?'Excellent':row.average>=14?'Très bien':row.average>=12?'Bien':row.average>=10?'Passable':'À renforcer'}</td></tr>)}</tbody></table>{!report.course_results.length&&<p className="p-8 text-center text-gray-500">Aucune note sur cette période.</p>}</div>
      <div className="grid md:grid-cols-4 gap-3 mt-5"><Stat label="Moyenne générale" value={report.overall_average==null?'—':`${Number(report.overall_average).toFixed(2)} / 20`} icon={Award}/><Stat label="Classement" value={report.rank?`${report.rank} / ${report.class_size}`:'—'}/><Stat label="Absences" value={report.absence_count}/><Stat label="Décision" value={meta.decision||'Non définie'}/></div>
      <div className="mt-5 rounded-xl bg-gray-50 p-4"><strong className="block">Appréciation générale</strong><p className="mt-1">{meta.appreciation||'Aucune appréciation.'}</p></div></div>
    </article>}
    {report && <div className="rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800 p-5"><div className="grid md:grid-cols-2 gap-4">{canManage?<><label><span className="font-bold block mb-1">Appréciation générale</span><textarea rows="4" value={meta.appreciation||''} onChange={(e)=>setMeta({...meta,appreciation:e.target.value})} className="w-full rounded-xl border dark:border-gray-700 bg-transparent p-3"/></label><div className="space-y-3"><label><span className="font-bold block mb-1">Décision du conseil</span><input value={meta.decision||''} onChange={(e)=>setMeta({...meta,decision:e.target.value})} placeholder="Admis, encouragements, redoublement…" className="w-full rounded-xl border dark:border-gray-700 bg-transparent p-3"/></label><label><span className="font-bold block mb-1">État</span><select value={meta.status||'draft'} onChange={(e)=>setMeta({...meta,status:e.target.value})} className="w-full rounded-xl border dark:border-gray-700 bg-transparent p-3"><option value="draft">Brouillon privé</option><option value="published">Publié pour l’étudiant</option></select></label></div></>:<p className="text-gray-500">Bulletin publié par l’établissement.</p>}</div><div className="flex flex-wrap justify-end gap-3 mt-4 border-t dark:border-gray-700 pt-4"><button onClick={()=>window.print()} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border dark:border-gray-700"><Printer size={18}/> Imprimer</button>{canManage&&<><button onClick={()=>save('draft')} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gray-700 text-white"><Save size={18}/> Enregistrer le brouillon</button><button onClick={()=>save('published')} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-green-600 text-white"><FileText size={18}/> Publier le bulletin</button></>}</div></div>}
  </div>;
};
const Select=({label,value,onChange,options=[]})=><label><span className="font-bold block mb-1">{label}</span><select value={value||''} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-xl border dark:border-gray-700 bg-white dark:bg-gray-900 p-3"><option value="">Sélectionner…</option>{options.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;
const Stat=({label,value,icon:Icon})=><div className="rounded-xl bg-gray-50 p-4">{Icon&&<Icon size={20} className="text-purple-600"/>}<small className="block text-gray-500 mt-1">{label}</small><strong className="text-xl">{value}</strong></div>;
export default ReportCardsPanel;
