import { useCallback, useEffect, useMemo, useState } from 'react';
import { Banknote, CalendarCheck, CheckCircle2, Edit3, Eye, FileCheck2, Loader2, Plus, RefreshCw, Save, Settings2, Trash2, WalletCards, X } from 'lucide-react';
import apiService from '../../services/api';
import { useNotifications } from '../../hooks/useNotifications';

const monthValue = () => new Date().toISOString().slice(0, 7);
const dateValue = () => new Date().toISOString().slice(0, 10);
const money = (value) => `${new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 2 }).format(Number(value || 0))} MGA`;
const statusLabels = { draft: 'Brouillon', approved: 'Validée', paid: 'Payée', cancelled: 'Annulée' };
const statColorClasses = {
  blue: 'text-blue-600',
  amber: 'text-amber-600',
  red: 'text-red-600',
  green: 'text-green-600',
};

const Payroll = () => {
  const { success, error: notifyError } = useNotifications();
  const [tab, setTab] = useState('attendance');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [period, setPeriod] = useState(monthValue());
  const [overview, setOverview] = useState({ teachers: [], policies: [], runs: [] });
  const [attendance, setAttendance] = useState([]);
  const [attendanceForm, setAttendanceForm] = useState({ teacher_id: '', attendance_date: dateValue(), status: 'present', late_minutes: 0, justification_status: 'none', justification_note: '', notes: '' });
  const [policyForm, setPolicyForm] = useState({ id: '', name: 'Politique standard', late_amount_per_minute: 0, absence_daily_multiplier: 1, standard_working_days: 22, maximum_deduction_percent: 30, is_active: true });
  const [selectedRun, setSelectedRun] = useState(null);

  const loadOverview = useCallback(async () => {
    try {
      setLoading(true);
      const response = await apiService.getPayroll('overview');
      const data = response?.data || { teachers: [], policies: [], runs: [] };
      setOverview(data);
      const active = data.policies?.find((item) => Number(item.is_active) === 1) || data.policies?.[0];
      if (active) setPolicyForm({ ...active, is_active: Number(active.is_active) === 1 });
    } catch (err) { notifyError(err.message); } finally { setLoading(false); }
  }, [notifyError]);

  const loadAttendance = useCallback(async () => {
    try { const response = await apiService.getPayroll('attendance', { period }); setAttendance(response?.data || []); } catch (err) { notifyError(err.message); }
  }, [notifyError, period]);

  useEffect(() => { loadOverview(); }, [loadOverview]);
  useEffect(() => { loadAttendance(); }, [loadAttendance]);

  const saveAttendance = async (event) => {
    event.preventDefault();
    try { setSaving(true); await apiService.createPayroll('attendance', attendanceForm); success('Présence du personnel enregistrée.'); await loadAttendance(); } catch (err) { notifyError(err.message); } finally { setSaving(false); }
  };
  const editAttendance = (item) => { setAttendanceForm({ teacher_id: item.teacher_id, attendance_date: item.attendance_date, status: item.status, late_minutes: item.late_minutes, justification_status: item.justification_status, justification_note: item.justification_note || '', notes: item.notes || '' }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const deleteAttendance = async (id) => { if (!window.confirm('Supprimer cette présence ?')) return; try { await apiService.deletePayroll('attendance', id); success('Présence supprimée.'); await loadAttendance(); } catch (err) { notifyError(err.message); } };
  const savePolicy = async (event) => { event.preventDefault(); try { setSaving(true); if (policyForm.id) await apiService.updatePayroll('policy', policyForm.id, policyForm); else await apiService.createPayroll('policy', policyForm); success('Politique de paie enregistrée.'); await loadOverview(); } catch (err) { notifyError(err.message); } finally { setSaving(false); } };
  const generate = async () => { const policy = overview.policies.find((item) => Number(item.is_active) === 1) || overview.policies[0]; if (!policy) return notifyError('Créez d’abord une politique de paie.'); try { setSaving(true); const response = await apiService.createPayroll('generate', { period, policy_id: policy.id }); success('Brouillon de paie généré.'); await loadOverview(); await openRun(response.data.id); setTab('runs'); } catch (err) { notifyError(err.message); } finally { setSaving(false); } };
  const openRun = async (id) => { try { const response = await apiService.getPayroll('run', { id }); setSelectedRun(response.data); } catch (err) { notifyError(err.message); } };
  const transition = async (id, status) => { const question = status === 'paid' ? 'Confirmer que cette paie a été versée ?' : status === 'cancelled' ? 'Annuler définitivement cette paie ?' : 'Valider définitivement ce brouillon de paie ?'; if (!window.confirm(question)) return; try { await apiService.updatePayroll('run', id, { status }); success(status === 'paid' ? 'Paie marquée comme versée.' : status === 'cancelled' ? 'Paie annulée.' : 'Paie validée.'); await loadOverview(); await openRun(id); } catch (err) { notifyError(err.message); } };
  const deleteRun = async (id) => { if (!window.confirm('Supprimer ce brouillon de paie ?')) return; try { await apiService.deletePayroll('run', id); setSelectedRun(null); await loadOverview(); success('Brouillon supprimé.'); } catch (err) { notifyError(err.message); } };
  const updateItem = async (item) => { try { await apiService.updatePayroll('item', item.id, item); success('Ligne de paie mise à jour.'); await openRun(item.payroll_run_id); } catch (err) { notifyError(err.message); } };

  const stats = useMemo(() => ({ late: attendance.filter((item) => item.status === 'late').length, absent: attendance.filter((item) => item.status === 'absent' && !['valid'].includes(item.justification_status)).length, justified: attendance.filter((item) => item.justification_status === 'valid').length }), [attendance]);
  if (loading) return <div className="min-h-[50vh] grid place-items-center"><Loader2 className="animate-spin text-purple-600" size={44} /></div>;

  return <section className="p-6 space-y-6">
    <header className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-wide text-purple-600">Ressources humaines</p><h1 className="text-4xl font-bold">Présence et paie du personnel</h1><p className="text-gray-500 mt-1">Retards, justifications, retenues configurables, validation et historique des salaires.</p></div><button onClick={() => { loadOverview(); loadAttendance(); }} className="h-fit inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border dark:border-gray-700"><RefreshCw size={18} /> Actualiser</button></header>
    <div className="rounded-2xl border border-amber-200 bg-amber-50 dark:bg-amber-950/30 dark:border-amber-900 p-4 text-amber-900 dark:text-amber-100"><strong>Contrôle obligatoire :</strong> les retenues sont des propositions calculées selon la politique interne. Elles doivent être vérifiées au regard du contrat et de la réglementation avant validation. Une absence avec justification « Valide » est toujours exclue de la retenue.</div>
    <nav className="flex gap-2 overflow-x-auto border-b dark:border-gray-700">
      {[['attendance','Présence du personnel',CalendarCheck],['policy','Règles de calcul',Settings2],['runs','Paies et bulletins de salaire',WalletCards]].map(([id,label,Icon]) => <button key={id} onClick={() => setTab(id)} className={`inline-flex items-center gap-2 px-4 py-3 font-bold border-b-4 whitespace-nowrap ${tab === id ? 'border-purple-600 text-purple-600' : 'border-transparent text-gray-500'}`}><Icon size={20} /> {label}</button>)}
    </nav>

    {tab === 'attendance' && <div className="space-y-5">
      <div className="grid md:grid-cols-4 gap-3"><Stat label="Employés actifs" value={overview.teachers.filter((item) => item.status === 'active').length} /><Stat label="Retards du mois" value={stats.late} color="amber" /><Stat label="Absences retenues" value={stats.absent} color="red" /><Stat label="Justifications validées" value={stats.justified} color="green" /></div>
      <form onSubmit={saveAttendance} className="rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800 p-5 space-y-4"><div className="flex justify-between"><div><h2 className="text-2xl font-bold">Enregistrer une présence</h2><p className="text-gray-500">La même date et le même enseignant mettent à jour la ligne existante.</p></div><input type="month" value={period} onChange={(event) => setPeriod(event.target.value)} className="h-fit rounded-xl border dark:border-gray-700 bg-transparent px-3 py-2" /></div><div className="grid md:grid-cols-3 xl:grid-cols-6 gap-3"><Select label="Employé" value={attendanceForm.teacher_id} onChange={(value) => setAttendanceForm({ ...attendanceForm, teacher_id: value })} options={overview.teachers.map((item) => ({ id: item.id, name: `${item.first_name} ${item.last_name}` }))} /><Input label="Date" type="date" value={attendanceForm.attendance_date} onChange={(value) => setAttendanceForm({ ...attendanceForm, attendance_date: value })} /><Select label="Statut" value={attendanceForm.status} onChange={(value) => setAttendanceForm({ ...attendanceForm, status: value, late_minutes: value === 'late' ? attendanceForm.late_minutes : 0 })} options={[['present','Présent'],['late','En retard'],['absent','Absent'],['excused','Excusé']].map(([id,name])=>({id,name}))} />{attendanceForm.status === 'late' && <Input label="Minutes de retard" type="number" value={attendanceForm.late_minutes} onChange={(value) => setAttendanceForm({ ...attendanceForm, late_minutes: value })} />}{['absent','excused'].includes(attendanceForm.status) && <Select label="Justification" value={attendanceForm.justification_status} onChange={(value) => setAttendanceForm({ ...attendanceForm, justification_status: value })} options={[['none','Aucune'],['pending','À vérifier'],['valid','Valide — aucune retenue'],['invalid','Refusée']].map(([id,name])=>({id,name}))} />}<Input label="Observation" value={attendanceForm.notes} onChange={(value) => setAttendanceForm({ ...attendanceForm, notes: value })} /><div className="flex items-end"><Submit saving={saving} /></div></div>{['pending','valid','invalid'].includes(attendanceForm.justification_status) && <Input label="Détail de la justification" value={attendanceForm.justification_note} onChange={(value) => setAttendanceForm({ ...attendanceForm, justification_note: value })} />}</form>
      <Table headers={['Date','Employé','Statut','Retard','Justification','Actions']} empty="Aucune présence enregistrée pour ce mois.">{attendance.map((item) => <tr key={item.id} className="border-t dark:border-gray-700"><Td>{new Date(`${item.attendance_date}T00:00:00`).toLocaleDateString('fr-FR')}</Td><Td strong>{item.teacher_name}<small className="block text-gray-400">{item.teacher_number}</small></Td><Td><Pill value={item.status} /></Td><Td>{item.late_minutes ? `${item.late_minutes} min` : '—'}</Td><Td><Pill value={item.justification_status} /></Td><Td><Action icon={Edit3} label="Modifier" onClick={() => editAttendance(item)} /><Action icon={Trash2} label="Supprimer" danger onClick={() => deleteAttendance(item.id)} /></Td></tr>)}</Table>
    </div>}

    {tab === 'policy' && <form onSubmit={savePolicy} className="max-w-5xl rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden"><div className="p-5 border-b dark:border-gray-700"><h2 className="text-2xl font-bold">Politique de retenue</h2><p className="text-gray-500">Modifiez les montants sans toucher au code. Le plafond s’applique aux retenues automatiques.</p></div><div className="p-5 grid md:grid-cols-2 xl:grid-cols-3 gap-4"><Input label="Nom de la politique" value={policyForm.name} onChange={(value) => setPolicyForm({ ...policyForm, name: value })} /><Input label="Montant par minute de retard (MGA)" type="number" value={policyForm.late_amount_per_minute} onChange={(value) => setPolicyForm({ ...policyForm, late_amount_per_minute: value })} /><Input label="Jours ouvrés du mois" type="number" value={policyForm.standard_working_days} onChange={(value) => setPolicyForm({ ...policyForm, standard_working_days: value })} /><Input label="Coefficient par absence injustifiée" type="number" value={policyForm.absence_daily_multiplier} onChange={(value) => setPolicyForm({ ...policyForm, absence_daily_multiplier: value })} /><Input label="Plafond de retenue automatique (%)" type="number" value={policyForm.maximum_deduction_percent} onChange={(value) => setPolicyForm({ ...policyForm, maximum_deduction_percent: value })} /><label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(Number(policyForm.is_active))} onChange={(event) => setPolicyForm({ ...policyForm, is_active: event.target.checked })} className="w-5 h-5 accent-purple-600" /><span><strong className="block">Politique active</strong><small className="text-gray-500">Utilisée lors de la prochaine génération.</small></span></label></div><div className="p-5 border-t dark:border-gray-700 flex justify-end"><Submit saving={saving} label="Enregistrer les règles" /></div></form>}

    {tab === 'runs' && <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-2xl font-bold">Paie mensuelle</h2><p className="text-gray-500">Générez un brouillon, contrôlez chaque ligne, puis validez et marquez le versement.</p></div><div className="flex gap-2"><input type="month" value={period} onChange={(event) => setPeriod(event.target.value)} className="rounded-xl border dark:border-gray-700 bg-transparent px-3" /><button onClick={generate} disabled={saving} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 text-white font-bold"><Plus size={18} /> Générer le brouillon</button></div></div><Table headers={['Mois','Politique','Employés','Net total','Statut','Actions']} empty="Aucune paie générée.">{overview.runs.map((run) => <tr key={run.id} className="border-t dark:border-gray-700"><Td strong>{new Date(`${run.period_month.slice(0,10)}T00:00:00`).toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</Td><Td>{run.policy_name}</Td><Td>{run.employee_count}</Td><Td strong>{money(run.total_net)}</Td><Td><Pill value={run.status} /></Td><Td><Action icon={Eye} label="Ouvrir" onClick={() => openRun(run.id)} />{run.status === 'draft' && <Action icon={Trash2} label="Supprimer" danger onClick={() => deleteRun(run.id)} />}</Td></tr>)}</Table>{selectedRun && <RunModal data={selectedRun} onClose={() => setSelectedRun(null)} onUpdateItem={updateItem} onTransition={transition} />}</div>}
  </section>;
};

const RunModal = ({ data, onClose, onUpdateItem, onTransition }) => <div className="app-modal-layer bg-black/60"><div className="app-modal-dialog w-full max-w-7xl rounded-2xl bg-white dark:bg-gray-800 shadow-2xl"><header className="p-5 border-b dark:border-gray-700 flex justify-between"><div><h2 className="text-3xl font-bold">Paie de {new Date(`${data.run.period_month.slice(0,10)}T00:00:00`).toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</h2><p className="text-gray-500">{data.run.policy_name} · {statusLabels[data.run.status]}</p></div><button onClick={onClose} aria-label="Fermer"><X size={26} /></button></header><div className="app-modal-body p-5 overflow-auto"><table className="w-full min-w-[1050px]"><thead className="bg-gray-50 dark:bg-gray-900"><tr>{['Employé','Base','Retards','Absences non justifiées','Retenues automatiques','Retenue manuelle','Prime','Net à payer','Action'].map((h)=><th key={h} className="text-left p-3">{h}</th>)}</tr></thead><tbody>{data.items.map((item)=><PayrollItem key={item.id} item={item} editable={data.run.status==='draft'} onSave={onUpdateItem} />)}</tbody></table></div><footer className="p-5 border-t dark:border-gray-700 flex justify-end gap-3">{data.run.status==='draft'&&<button onClick={()=>onTransition(data.run.id,'approved')} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-green-600 text-white font-bold"><CheckCircle2 size={19}/> Valider la paie</button>}{data.run.status==='approved'&&<button onClick={()=>onTransition(data.run.id,'paid')} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-blue-600 text-white font-bold"><Banknote size={19}/> Confirmer le versement</button>}</footer></div></div>;
const PayrollItem=({item,editable,onSave})=>{const [draft,setDraft]=useState(item);useEffect(()=>setDraft(item),[item]);return <tr className="border-t dark:border-gray-700"><Td strong>{item.teacher_name}<small className="block text-gray-400">{item.teacher_number}</small></Td><Td>{money(item.base_salary)}</Td><Td>{item.late_count} · {item.late_minutes} min</Td><Td>{item.unjustified_absences}</Td><Td><span className="text-red-600">-{money(Number(item.late_deduction)+Number(item.absence_deduction))}</span></Td><Td>{editable?<input type="number" min="0" value={draft.manual_deduction} onChange={(e)=>setDraft({...draft,manual_deduction:e.target.value})} className="w-28 rounded-lg border dark:border-gray-700 bg-transparent p-2"/>:money(item.manual_deduction)}</Td><Td>{editable?<input type="number" min="0" value={draft.bonus_amount} onChange={(e)=>setDraft({...draft,bonus_amount:e.target.value})} className="w-28 rounded-lg border dark:border-gray-700 bg-transparent p-2"/>:money(item.bonus_amount)}</Td><Td strong>{money(item.net_salary)}</Td><Td>{editable&&<Action icon={Save} label="Enregistrer" onClick={()=>onSave(draft)}/>}</Td></tr>};
const Stat=({label,value,color='blue'})=><div className="rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800 p-4"><small className="text-gray-500">{label}</small><strong className={`block text-3xl ${statColorClasses[color] || statColorClasses.blue}`}>{value}</strong></div>;
const Table=({headers,children,empty})=><div className="overflow-x-auto rounded-2xl border dark:border-gray-700 bg-white dark:bg-gray-800"><table className="w-full"><thead className="bg-gray-50 dark:bg-gray-900"><tr>{headers.map((h)=><th key={h} className="text-left p-3 whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{children}</tbody></table>{!children?.length&&<p className="p-10 text-center text-gray-500">{empty}</p>}</div>;
const Input=({label,value,onChange,type='text'})=><label className="block"><span className="block font-semibold mb-1">{label}</span><input type={type} value={value??''} onChange={(e)=>onChange(e.target.value)} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined} required className="w-full rounded-xl border dark:border-gray-700 bg-transparent px-3 py-2.5"/></label>;
const Select=({label,value,onChange,options})=><label className="block"><span className="block font-semibold mb-1">{label}</span><select value={value??''} onChange={(e)=>onChange(e.target.value)} required className="w-full rounded-xl border dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2.5"><option value="">Sélectionner…</option>{options.map((o)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;
const Submit=({saving,label='Enregistrer'})=><button type="submit" disabled={saving} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-purple-600 text-white font-bold">{saving?<Loader2 size={18} className="animate-spin"/>:<Save size={18}/>} {label}</button>;
const Action=({icon:Icon,label,onClick,danger})=><button type="button" onClick={onClick} title={label} aria-label={label} className={`inline-flex items-center gap-1 px-2.5 py-1.5 rounded-lg mr-1 font-semibold ${danger?'text-red-600 hover:bg-red-50':'text-blue-600 hover:bg-blue-50'}`}><Icon size={17}/><span className="hidden 2xl:inline">{label}</span></button>;
const Td=({children,strong})=><td className={`p-3 ${strong?'font-bold':'text-gray-600 dark:text-gray-300'}`}>{children}</td>;
const Pill=({value})=>{const map={present:'Présent',late:'Retard',absent:'Absent',excused:'Excusé',none:'Aucune',pending:'À vérifier',valid:'Valide',invalid:'Refusée',...statusLabels};const colors={present:'bg-green-100 text-green-700',valid:'bg-green-100 text-green-700',paid:'bg-green-100 text-green-700',late:'bg-amber-100 text-amber-700',pending:'bg-amber-100 text-amber-700',approved:'bg-blue-100 text-blue-700',absent:'bg-red-100 text-red-700',invalid:'bg-red-100 text-red-700',cancelled:'bg-red-100 text-red-700'};return <span className={`px-2.5 py-1 rounded-full text-sm font-bold ${colors[value]||'bg-gray-100 text-gray-700'}`}>{map[value]||value}</span>};
export default Payroll;
